// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountQuotaWindow = { limitId: string, model: string | null, remainingPercent: number, windowMinutes: number, resetsAt: number | null, };
