// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AccountPool = { name: string,
/**
 * Ordered aliases. The order breaks quota and reset-credit ties.
 */
accounts: Array<string>,
/**
 * Use existing banked credits only when every eligible account is weekly exhausted.
 */
redeemWeeklyResets: boolean, };
