// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ManagedAccount } from "./ManagedAccount";
import type { PoolWaitReason } from "./PoolWaitReason";

export type AccountPoolEvent = { "type": "selected", account: ManagedAccount, } | { "type": "switched", account: string, previousAccount: string, } | { "type": "redeemed", account: string, } | { "type": "waiting", account: string, reason: PoolWaitReason, nextCheckAt: number, };
