// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountSelection } from "./AccountSelection";
import type { ManagedAccountAction } from "./ManagedAccountAction";

export type ManagedAccountParams = { action: ManagedAccountAction,
/**
 * Session selection for `resolve`; omitted selection uses saved state or the user default.
 */
accountSelection?: AccountSelection | null, threadId?: string | null, alias?: string | null,
/**
 * Use device-code login for `add`; defaults to browser OAuth.
 */
deviceAuth?: boolean | null, model?: string | null, cursor?: string | null, limit?: number | null, };
