// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountQuotaWindow } from "./AccountQuotaWindow";
import type { BankedReset } from "./BankedReset";
import type { ManagedAccount } from "./ManagedAccount";

export type ManagedAccountUsage = { account: ManagedAccount, pools: Array<string>, model: string | null, modelSupported: boolean | null, ordinaryUsageAllowed: boolean | null, windows: Array<AccountQuotaWindow>, availableResets: number | null,
/**
 * Null means details are unknown, including failed reads.
 */
resets: Array<BankedReset> | null, checkedAt: number, error: string | null, };
