// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountSelection } from "./AccountSelection";
import type { GetAccountResponse } from "./GetAccountResponse";
import type { LoginAccountResponse } from "./LoginAccountResponse";
import type { ManagedAccount } from "./ManagedAccount";
import type { ManagedAccountUsage } from "./ManagedAccountUsage";
import type { Model } from "./Model";

export type ManagedAccountResponse = {
/**
 * Null means this selection uses legacy authentication.
 */
resolved: GetAccountResponse | null, models: Array<Model> | null, data: Array<ManagedAccount>, nextCursor: string | null, usage: Array<ManagedAccountUsage>, login: LoginAccountResponse | null, defaultSelection: AccountSelection | null, };
