// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPool } from "./AccountPool";
import type { ManagedPoolAction } from "./ManagedPoolAction";

export type ManagedPoolParams = { action: ManagedPoolAction, name?: string | null, pool?: AccountPool | null, cursor?: string | null, limit?: number | null, };
