// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountPool } from "./AccountPool";
import type { AccountSelection } from "./AccountSelection";

export type ManagedPoolResponse = { data: Array<AccountPool>, nextCursor: string | null, defaultSelection: AccountSelection | null, };
