// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution mode for reasoning (`reasoning.mode` in the Responses API). Independent of effort,
 * which sets how much reasoning happens within the mode. The API defaults to `standard`.
 * See https://developers.openai.com/api/docs/guides/reasoning?api-mode=responses#reasoning-mode
 */
export type ReasoningMode = "standard" | "pro";
